--- #YAML:1.0
name:                Tk-ContextHelp
version:             0.12
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Tk:                            402.002
    Tk::InputO:                    0
    Tk::Pod:                       4
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
